# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

# 获取项目根目录
root = Path(SPECDIR).absolute()

# 分析主应用
a = Analysis(
    ['app.py'],
    pathex=[str(root)],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('desensitizer.py', '.'),
    ],
    hiddenimports=[
        'pandas',
        'pandas._libs.tslibs.base',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.conversion',
        'pandas._libs.tslibs.fields',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.ccalendar',
        'pandas._libs.tslibs.dtypes',
        'pandas._libs.properties',
        'pandas._libs.hashtable',
        'pandas._libs.index',
        'pandas._libs.indexing',
        'pandas._libs.internals',
        'pandas._libs.interval',
        'pandas._libs.join',
        'pandas._libs.lib',
        'pandas._libs.missing',
        'pandas._libs.parsers',
        'pandas._libs.reduction',
        'pandas._libs.ops',
        'pandas._libs.ops_dispatch',
        'pandas._libs.reshape',
        'pandas._libs.sparse',
        'pandas._libs.testing',
        'pandas._libs.writers',
        'pandas._libs.window.aggregations',
        'pandas._libs.window.indexers',
        'pandas.io.excel._openpyxl',
        'pandas.io.excel._xlrd',
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.cell._writer',
        'openpyxl.chart',
        'openpyxl.chartsheet',
        'openpyxl.comments',
        'openpyxl.compat',
        'openpyxl.descriptors',
        'openpyxl.drawing',
        'openpyxl.formatting',
        'openpyxl.formula',
        'openpyxl.packaging',
        'openpyxl.pivot',
        'openpyxl.reader',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.xml',
        'openpyxl.xml.functions',
        'flask',
        'werkzeug',
        'jinja2',
        'jinja2.ext',
        'markupsafe',
        'itsdangerous',
        'click',
        'numpy',
        'numpy.core',
        'numpy.core._dtype_ctypes',
        'numpy.core._multiarray_tests',
        'numpy.core._multiarray_umath',
        'numpy.core._operand_flag_tests',
        'numpy.core._rational_tests',
        'numpy.core._struct_ufunc_tests',
        'numpy.core._umath_tests',
        'numpy.fft',
        'numpy.lib',
        'numpy.linalg',
        'numpy.ma',
        'numpy.matrixlib',
        'numpy.polynomial',
        'numpy.random',
        'numpy.testing',
        'xml.etree.ElementTree',
        'xml.etree.cElementTree',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'tkinter',
        'unittest',
        'pydoc',
        'pdb',
        'doctest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Excel数据脱敏工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
